# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac1c9c50de2b913307581494bf7b03a0169043b7cad2c9bb3e88831e60a5f474704d06ed1a0899b1ccdc33a114805debd2df6fbb24db4e1495571a81ce793d3b

test:
  secret_key_base: 7ba4a31d7c52a303712eb8b96a6c7b843f9de4ef13401fe9c6ad4401c070e6448a67dc72043e89a676191f071c6f58aad8780260e186463425c17ba4b7e04b7d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
